export const produtoVendaOptions = [
  { name: "BOBINA TERMICA 55MM X300M", categoria: "1" },
  { name: "CARTAO CARTOLINA", categoria: "1" },
  { name: "CARTAO DE PROXIMIDADE ISO CARD FINO", categoria: "1" },
  { name: "CHAPEIRA 10 LUGARES", categoria: "1" },
  { name: "CHAPEIRA 15 LUGARES", categoria: "1" },
  { name: "CHAPEIRA 25 LUGARES", categoria: "1" },
  { name: "CHAPEIRA 5 LUGARES", categoria: "1" },
  { name: "CHAPEIRA 50 LUGARES", categoria: "1" },
  {
    name: "FECHADURA SOBREPOR DIGITAL BIOMETRIA + SMARTCARD +TECLADO PORTA DE MADEIRA",
    categoria: "1",
  },
  { name: "FITA DE IMPRESSAO PRINTNOX", categoria: "1" },
  { name: "HORA TECNICA", categoria: "1" },
  { name: "REL PONTO INFO DIXI IREP FACIAL PROX WIFI", categoria: "1" },
  { name: "REL PONTO INFO DIXI IREP I4 BIO VERDE PROX WIFI", categoria: "1" },
  {
    name: "REL PONTO INFO DIXI IREP I4 BIO VERMELHO 4M PROX WIFI",
    categoria: "1",
  },
  {
    name: "REL PONTO INFO DIXI IREP I4 BIO VERMELHO PROX WIFI",
    categoria: "1",
  },
  { name: "REL PONTO INFO DIXI SINDNOX BIO/PROX", categoria: "1" },
  { name: "REL PONTO INFO DIXI SINDNOX FACIAL PROX WIFI", categoria: "1" },
  {
    name: "REL PONTO INFO HENRY HEXA ADV B BIO VERDE  PROX WIFI",
    categoria: "1",
  },
  {
    name: "REL PONTO INFO HENRY HEXA ADV B BIO VERMELHA  PROX WIFI",
    categoria: "1",
  },
  {
    name: "REL PONTO INFO HENRY HEXA ADV B BIO VERMELHA 4M PROX WIFI",
    categoria: "1",
  },
  {
    name: "REL PONTO INFO HENRY PONTO E ADV D BIO VERDE PROX COM WIFI",
    categoria: "1",
  },
  {
    name: "REL PONTO INFO HENRY PONTO E ADV D BIO VERMELHO PROX COM WIFI",
    categoria: "1",
  },
  {
    name: "REL PONTO INFO HENRY SF ADV R2 BIO VERDE PROX WIFI",
    categoria: "1",
  },
  {
    name: "REL PONTO INFO HENRY SF ADV R2 BIO VERMELHO 4M PROX  WIFI",
    categoria: "1",
  },
  {
    name: "REL PONTO INFO HENRY SF ADV R2 BIO VERMELHO PROX WIFI",
    categoria: "1",
  },
  { name: "RELOGIO DE PONTO DIXI PRINTNOX", categoria: "1" },
  { name: "SIRENE 110/220V", categoria: "1" },
  { name: "TROCA DE PLACA", categoria: "1" },
  { name: "VIGIA BLUE", categoria: "1" },
  { name: "VIGIA ONLINE", categoria: "1" },
  { name: "BATERIA PARA CARTOGRAFICO", categoria: "1" },
  { name: "BATERIA PARA VIGIA BLUE", categoria: "1" },
  { name: "BUTTON", categoria: "1" },
  { name: "CARTAO DE PROXIMIDADE PERSONALIZADO", categoria: "1" },
  { name: "CORDAO PERSONALIZADO", categoria: "1" },
  { name: "FONTE IREP", categoria: "1" },
  { name: "GUILHOTINA", categoria: "1" },
  { name: "NOBREAK", categoria: "1" },
  { name: "PORTA CRACHA", categoria: "1" },
  { name: "TAGS PROXIMIDADE", categoria: "1" },
  { name: "VIGIA BASTAO BLUE", categoria: "1" },
  { name: "VIGIA PROX (L8)", categoria: "1" },
  { name: "COLETOR DIXI FACIAL", categoria: "1" },
  { name: "ROLETE", categoria: "1" },
  { name: "VISITA TECNICA", categoria: "1" },
  { name: "CONTROLE DE ACESSO FACIAL", categoria: "1" },
];

export const produtoContratoOptions = [
  { name: "PACK de Implantacao Premium", categoria: "2" },
  { name: "ADITIVO DE CONTRATO", categoria: "2" },
  { name: "CARTOGRAFICO + SUPORTE", categoria: "2" },
  { name: "CARTOGRAFICO SEM SUPORTE", categoria: "2" },
  { name: "IREP + SOFTWARE STANDARD + SUPORTE", categoria: "2" },
  { name: "IREP + SOFTWARE STANDARD SEM SUPORTE", categoria: "2" },
  { name: "IREP + SOFTWARE PREMIUM + SUPORTE", categoria: "2" },
  { name: "IREP + SOFTWARE PREMIUM", categoria: "2" },
  { name: "IREP FACIAL + SOFTWARE STANDARD + SUPORTE", categoria: "2" },
  { name: "IREP FACIAL + SOFTWARE STANDARD SEM SUPORTE", categoria: "2" },
  { name: "IREP FACIAL + SOFTWARE PREMIUM + SUPORTE", categoria: "2" },
  { name: "IREP FACIAL + SOFTWARE PREMIUM SEM SUPORTE ", categoria: "2" },
  { name: "IREP FACIAL", categoria: "2" },
  { name: "IREP", categoria: "2" },
  { name: "MOBILE + SUPORTE", categoria: "2" },
  { name: "MOBILE SEM SUPORTE", categoria: "2" },
  { name: "PACK IMPLANTACAO", categoria: "2" },
  { name: "SINDNOX + SOFTWARE STANDARD + SUPORTE", categoria: "2" },
  { name: "SINDNOX + SOFTWARE STANDARD SEM SUPORTE", categoria: "2" },
  { name: "SINDNOX + SOFTWARE PREMIUM + SUPORTE", categoria: "2" },
  { name: "SINDNOX + SOFTWARE PREMIUM SEM SUPORTE ", categoria: "2" },
  { name: "SINDNOX FACIAL + SOFTWARE STANDARD + SUPORTE", categoria: "2" },
  { name: "SINDNOX FACIAL + SOFTWARE STANDARD SEM SUPORTE", categoria: "2" },
  { name: "SINDNOX FACIAL + SOFTWARE PREMIUM + SUPORTE", categoria: "2" },
  { name: "SINDNOX FACIAL + SOFTWARE PREMIUM SEM SUPORTE ", categoria: "2" },
  { name: "SINDNOX FACIAL", categoria: "2" },
  { name: "SINDNOX", categoria: "2" },
  { name: "SOFTWARE CORPORATIVO + MOBILE + SUPORTE", categoria: "2" },
  { name: "SOFTWARE CORPORATIVO + MOBILE SEM SUPORTE", categoria: "2" },
  { name: "SOFTWARE DIXI STANDARD COM SUPORTE", categoria: "2" },
  { name: "SOFTWARE DIXI STANDARD SEM SUPORTE", categoria: "2" },
  { name: "SOFTWARE STANDARD + SUPORTE", categoria: "2" },
  { name: "SOFTWARE STANDARD SEM SUPORTE", categoria: "2" },
  { name: "SOFTWARE PREMIUM + MOBILE + SUPORTE", categoria: "2" },
  { name: "SOFTWARE PREMIUM + MOBILE SEM SUPORTE", categoria: "2" },
  { name: "SOFTWARE PREMIUM + SUPORTE", categoria: "2" },
  { name: "SOFTWARE PREMIUM SEM SUPORTE", categoria: "2" },
  { name: "SUPORTE", categoria: "2" },
  { name: "COLETOR DIXI FACIAL", categoria: "2" },
  { name: "COLETOR DIXI FACIAL + SUPORTE", categoria: "2" },
  { name: "COLETOR DIXI FACIAL + SOFTWARE STANDARD", categoria: "2" },
  {
    name: "COLETOR DIXI FACIAL + SOFTWARE STANDARD SEM SUPORTE",
    categoria: "2",
  },
  { name: "COLETOR DIXI FACIAL + SOFTWARE STANDARD + SUPORTE", categoria: "2" },
  { name: "COLETOR DIXI FACIAL + SOFTWARE PREMIUM", categoria: "2" },
  {
    name: "COLETOR DIXI FACIAL + SOFTWARE PREMIUM SEM SUPORTE",
    categoria: "2",
  },
  { name: "COLETOR DIXI FACIAL + SOFTWARE PREMIUM + SUPORTE", categoria: "2" },
  { name: "COLETOR DIXI FACIAL + SOFTWARE CORPORATIVO", categoria: "2" },
  {
    name: "COLETOR DIXI FACIAL + SOFTWARE CORPORATIVO SEM SUPORTE",
    categoria: "2",
  },
  {
    name: "COLETOR DIXI FACIAL + SOFTWARE CORPORATIVO + SUPORTE",
    categoria: "2",
  },
  { name: "SOFTWARE CORPORATIVO + SUPORTE", categoria: "2" },
  { name: "SOFTWARE CORPORATIVO SEM SUPORTE", categoria: "2" },
  { name: "SUPORTE CORPORATIVO", categoria: "2" },
  { name: "VIGIA BLUE", categoria: "2" },
  { name: "VIGIA PROX (L8)", categoria: "2" },
];
