export const statusOptions = [
  "Aberta",
  "Cancelada",
  "Contrato",
  "Atrelado",
  "Aguardando Aceite",
  "Aguardando Pagamento",
  "Aguardando Pagamento Cielo",
  "Teste 7 Dias",
  "Nota Fiscal",
  "Lançado OMIE",
  "Emitir NFSe",
  "Omie Contrato",
  "Enviado",
  "Troca",
  "Em Producao",
  "Recusado",
  "Edicao",
  "Liberado Financeiro",
  "Bonificacao",
];
