export const statusOptions = [
  { name: "Aberta", value: "Aberta" },
  { name: "Cancelada", value: "Cancelada" },
  { name: "Contrato", value: "Contrato" },
  { name: "Atrelado", value: "Atrelado" },
  { name: "Aguardando Aceite", value: "Aguardando Aceite" },
  { name: "Aguardando Pagamento", value: "Aguardando Pagamento" },
  { name: "Aguardando Pagamento Cielo", value: "Aguardando Pagamento Cielo" },
  { name: "Teste 7 Dias", value: "Teste 7 Dias" },
  { name: "Nota Fiscal", value: "Nota Fiscal" },
  { name: "Lançado OMIE", value: "Lançado OMIE" },
  { name: "Emitir NFSe", value: "Emitir NFSe" },
  { name: "Omie Contrato", value: "Omie Contrato" },
  { name: "Enviado", value: "Enviado" },
  { name: "Troca", value: "Troca" },
  { name: "Em Producao", value: "Em Producao" },
  { name: "Recusado", value: "Recusado" },
  { name: "Edicao", value: "Edicao" },
  { name: "Liberado Financeiro", value: "Liberado Financeiro" },
  { name: "Bonificacao", value: "Bonificacao" },
];
